### ISSUE TITLE
this is trash

### ISSUE THREAD

**Issue by BradF-99** [Assasindie/PiProject#1]
# i git cloned this to my pc and nothing happened please help

**Comment by BradF-99** [comment]
Bump, still waiting on a response closed for no reason.

**Comment by aXises** [comment]
您好，可能是您的电脑上没有正确安装软件包，请更新到最新版本的窗口8并在之后发回任何错误日志。谢谢

**Comment by BradF-99** [comment]
Hello (sorry for bad English)

**Comment by Assasindie** [comment]
Hello (resolved)
